language: node_js
node_js:
  - 'stable'
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: public
  name: Selvin11
  repo: Selvin11/Selvin11.github.io
  project_name: Blog
  target_branch: blog
  on:
    branch: master
cache:
  directories:
  - node_modules # NPM packages
